import { WebHttpContextMap } from '../TYPES'

export const WEB_HTTP_CONTEXT_MAP: WebHttpContextMap = {
  SESSION_ID: 'SESSION_ID',
  API_KEY: 'API_KEY',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  PUBLIC_KEY: 'PUBLIC_KEY',
  CLIENT_ID: 'CLIENT_ID',
  AUTHENTICATION_TOKEN_KEY: 'AUTHENTICATION_TOKEN_KEY'
}
