const CONTEXT = {
  SESSION_ID: 'SESSION_ID',
  API_KEY: 'API_KEY',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  PUBLIC_KEY: 'PUBLIC_KEY',
  CLIENT_ID: 'CLIENT_ID'
}

export default CONTEXT
