const ACCESS_TOKEN_REQUEST_HEADER_KEY = 'X-Access-Token'
const ACCESS_TOKEN_RESPONSE_HEADER_KEY = 'X-Access-Token'

const SESSION_ID_REQUEST_HEADER_KEY = 'X-Session-ID'
const SESSION_ID_RESPONSE_HEADER_KEY = 'X-Session-ID'

const REQUEST_ID_REQUEST_HEADER_KEY = 'X-Request-ID'

const API_KEY_REQUEST_HEADER_KEY = 'X-API-Key'

const APP_UID_REQUEST_HEADER_KEY = 'X-App-UID'
const APP_UID_RESPONSE_HEADER_KEY = 'X-App-UID'

const ENCRYPTION_KEY_REQUEST_HEADER_KEY = 'X-API-Encryption-Key'
const CLIENT_ID_REQUEST_HEADER_KEY = 'X-API-Client-Id'
const CLIENT_ID_REQUEST_HEADER_VALUE = 'BROWSER'

const HEADERS = {
  ACCESS_TOKEN_REQUEST_HEADER_KEY,
  ACCESS_TOKEN_RESPONSE_HEADER_KEY,

  SESSION_ID_REQUEST_HEADER_KEY,
  SESSION_ID_RESPONSE_HEADER_KEY,

  REQUEST_ID_REQUEST_HEADER_KEY,

  API_KEY_REQUEST_HEADER_KEY,

  APP_UID_REQUEST_HEADER_KEY,
  APP_UID_RESPONSE_HEADER_KEY,

  ENCRYPTION_KEY_REQUEST_HEADER_KEY,
  CLIENT_ID_REQUEST_HEADER_KEY,
  CLIENT_ID_REQUEST_HEADER_VALUE
}

export default HEADERS
